apiVersion: apps/v1
kind: Deployment
metadata:
  name: plex-deploy
  namespace: plextv
  labels:
    app: plextv
  annotations:
    openshift.io/scc: anyuid
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: plextv
  template:
    metadata:
      labels:
        app: plextv
      annotations:
        k8s.v1.cni.cncf.io/networks: 'default/macvlan'
        # v1.multus-cni.io/default-network: 'default/macvlan'
    spec:
      serviceAccountName: plex-sa
      hostname: ocp-plex
      containers:
      - name: plextv
        image: shaker242/plex:latest
        imagePullPolicy: Always
        # resources:
        #     limits:
        #       cpu: 500m
        #       memory: 1Gi
        ports:
          - name: plex
            containerPort: 32400
        env:
        - name: TZ
          value: "America/New_York"
        - name: PLEX_CLAIM
          # Get your claim key, log into plex.tv with your account and visit plex.tv/claim, use the key below.
          value: claim-igRn1fzAhWXEG1oJePtT # claims only last 4 mins
        - name: ALLOWED_NETWORKS # skip logins from trusted "local" networks
          value: 192.168.11.0/24,172.16.1.0/26
        volumeMounts:
          - name: plex-config
            mountPath: /config
          # - name: plex-transcode
          #   # For remote sessions, it's good to use a transcoder; I put it in memory below.
          #   # Note: although limted to 2Gi, I have still seen it grow upwards of 10Gi.
          #   mountPath: /transcode
          - name: plex-media
            mountPath: /media
      volumes:
      - name: plex-config
        persistentVolumeClaim:
          claimName: pvc-plexfs-config
      # - name: plex-transcode
      #   emptyDir:
      #     medium: Memory
      #     sizeLimit: 2Gi
      - name: plex-media
        persistentVolumeClaim:
          claimName: pvc-plexfs-media
