---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: plex-sa
  namespace: plextv
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: plex-role
  namespace: plextv
  labels:
    app: plextv
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - pods/attach
      - pods/exec
      - pods/portforward
      - pods/proxy
    verbs:
      - create
      - delete
      - deletecollection
      - get
      - list
      - patch
      - update
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: plex-rolebinding
  namespace: plextv
  labels:
    app: plextv
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: plex-role
subjects:
  - kind: ServiceAccount
    name: plex-sa
    namespace: plextv