---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: plextv
  name: ocp-plex
  namespace: plextv
spec:
  host: #ocp-plex.redcloud.land
  port:
    targetPort: plex
  to:
    kind: Service
    name: plex-port
    weight: 100
  wildcardPolicy: None
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: plextv
  name: http
  namespace: plextv
spec:
  host: #http-plex.apps.okd.redcloud.land
  port:
    targetPort: http
  to:
    kind: Service
    name: plex-web
    weight: 100
  wildcardPolicy: None
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: plextv
  name: https
  namespace: plextv
spec:
  host: #https-plex.apps.okd.redcloud.land
  port:
    targetPort: https
  tls:
    insecureEdgeTerminationPolicy: None
    termination: passthrough
  to:
    kind: Service
    name: plex-web
    weight: 100
  wildcardPolicy: None