name: Linting Kubernetes ☸️
on:
 pull_request:
    branches:
    - '!main'
    paths: 
    - './**.yaml'
    - './**.yml'
        
 workflow_dispatch:

jobs:
  k8s-lint:
    uses: ocpdude/reusable/.github/workflows/linter.yaml@main
    with:
      language: YamlLint, kubeval
